# Generated by Django 5.0.6 on 2024-07-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_review_name_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='origin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coffee',
            name='roast_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='snack',
            name='ingredients',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='image',
            field=models.ImageField(default='coffees/default.jpg', upload_to='coffees/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coffee',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='snack',
            name='image',
            field=models.ImageField(upload_to='desserts/'),
        ),
        migrations.AlterField(
            model_name='snack',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='snack',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
