# Generated by Django 5.0.6 on 2024-07-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_coffee_origin_coffee_roast_level_snack_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
