# Generated by Django 5.0.6 on 2024-07-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_coffee_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ingredients', models.TextField()),
                ('image', models.ImageField(upload_to='desserts/')),
            ],
        ),
        migrations.AlterField(
            model_name='snack',
            name='image',
            field=models.ImageField(upload_to='snacks/'),
        ),
        migrations.AlterField(
            model_name='snack',
            name='ingredients',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='snack',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
